name: Go package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        GOOS: [linuux, darwin, windows]
        GOARCH: [amd64, arm64]
        include:
          - GOOS: windows
            EXE: .exe
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Build
        run: go build -o build/hello-${GOOS}-${GOARCH}${EXE}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: build/
          retention-days: 1
